src/com/ofbox/davivienda/h2h/abstraccion/dto/HthProcesoMonitoreo.java
package com.ofbox.davivienda.h2h.abstraccion.dto;
import java.lang.Long;
import java.io.Serializable;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import com.ofbox.f3.app.distribuibles.abstraccion.comunes.validacion.UtileriaDeTiposDeDatos;
/**
 * Clase POJO(Plain Old Java Object), que permite almacenar los valores de las propiedades de un objeto de negocio, tambi&eacute;n conocido como DTO(Data Transfer Object).
 * Este DTO es el que viaja entre la capa DAO y la capa de negocios, y que posteriormente es manipulado en la capa de la vista.  
 * 
 * @author Systems Out of the Box
 * @version f3.1 --
 */
 
public class HthProcesoMonitoreo implements Serializable{
public static final String convenio_PE_ACH_PE = "PE";
public static final String convenio_PE_ACH_ACH = "ACH";
public static final String convenio_PS = "PS";
public static final String convenio_TEXT = "TEXT";
public static final String convenio_nombre_PLANILLA = "PLANILLA";
public static final String convenio_nombre_PROVEEDORES = "PROVEEDORES";
public static final String convenio_nombre_COBROS = "COBROS";
public static final String convenio_nombre_CHEQUES = "CHEQUES";
public static final String convenio_nombre_PAGO_PLANILLAS_ACH = "ACH_PLANILLA";
public static final String convenio_nombre_PAGO_PROVEEDORES_ACH = "ACH_PROVEEDORES";
public static final String linea_encabezado_SI = "S";
public static final String linea_encabezado_NO = "N";
public static final String procesamiento_superusuario_SI = "S";
public static final String procesamiento_superusuario_NO = "N";
public static final String estado_ACTIVADO = "A";
public static final String estado_DESACTIVADO = "D";
	/**
     * Atributo que almacena el valor que funciona como llave para un objeto de Negocio.
     */
     private Long idProcesoMonitoreo;
    /**
     * Devuelve el objeto que almacena el identificador del DTO.
     * @return
     */
     public Long getDtoId(){
        return idProcesoMonitoreo;
     }
    /**
     * Coloca el objeto que almacena el identificador del DTO.
     * @param dtoId objeto que almacena la llave que identifica al DTO. 
     */
     public void setDtoId(Long dtoId){
     	this.idProcesoMonitoreo = dtoId;
     }
    
    /** Atributos que almacenan los valores para las propiedades de un objeto DTO correspondiente a un objeto Negocio. */
     
     private Long convenio;
	 
     private Long tipoconvenio;
	 
     private String convenioPEACH;
	 
     private String convenioNombre;
	 
     private String nombreArchivo;
	 
     private String rutaSftp;
	 
     private String rutaArchivosIn;
	 
     private String rutaArchivosOut;
	 
     private String rutaProcesados;
	 
     private Long tiempoMonitoreo;
	 
     private String lineaEncabezado;
	 
     private String procesamientoSuperusuario;
	 
     private java.math.BigDecimal montoMaximoProcesar;
	 
     private String estado;
	 
     private String usuarioCreacion;
	 
     private java.util.Date fechaCreacion;
	 
     private String usuarioUltAct;
	 
     private java.util.Date fechaUltAct;
	 
     private String emailCliente;
     
     private String pmHostSftp;
	 
     private String pmPuertoSftp;
	 
     private String pmUsuarioSftp;
	 
     private String pmPasswordSftp;
	 
     private String pmLlaveSftp;
	 

    /**
     * Atributos que almacenan los DTOs de objetos de negocios que funcionan como objetos foraneos.
     */    		
    private BsCliente bsCliente;
    private HthVistaConvenio hthVistaConvenio;
    private BsEmpresaodepto bsEmpresaodepto;
    private HthFormatoEncabezado hthFormatoEncabezado;
    private HthFormato hthFormato;


     
    
    /** M&eacute;todos que devuelven y colocan los valores de los atributos respectivos del DTO. */
     
     public Long getIdProcesoMonitoreo(){
		return this.idProcesoMonitoreo;         
     }

     public void setIdProcesoMonitoreo( Long idProcesoMonitoreo){
		this.idProcesoMonitoreo = idProcesoMonitoreo;
     }
     public Long getConvenio(){
		return this.convenio;         
     }

     public void setConvenio( Long convenio){
		this.convenio = convenio;
     }
     public Long getTipoconvenio(){
		return this.tipoconvenio;         
     }

     public void setTipoconvenio( Long tipoconvenio){
		this.tipoconvenio = tipoconvenio;
     }
     public String getConvenioPEACH(){
		return this.convenioPEACH;         
     }

     public void setConvenioPEACH( String convenioPEACH){
		this.convenioPEACH = convenioPEACH;
     }
     public String getConvenioNombre(){
		return this.convenioNombre;         
     }

     public void setConvenioNombre( String convenioNombre){
		this.convenioNombre = convenioNombre;
     }
     public String getNombreArchivo(){
		return this.nombreArchivo;         
     }

     public void setNombreArchivo( String nombreArchivo){
		this.nombreArchivo = nombreArchivo;
     }
     public String getRutaSftp(){
		return this.rutaSftp;         
     }

     public void setRutaSftp( String rutaSftp){
		this.rutaSftp = rutaSftp;
     }
     public String getRutaArchivosIn(){
		return this.rutaArchivosIn;         
     }

     public void setRutaArchivosIn( String rutaArchivosIn){
		this.rutaArchivosIn = rutaArchivosIn;
     }
     public String getRutaArchivosOut(){
		return this.rutaArchivosOut;         
     }

     public void setRutaArchivosOut( String rutaArchivosOut){
		this.rutaArchivosOut = rutaArchivosOut;
     }
     public String getRutaProcesados(){
		return this.rutaProcesados;         
     }

     public void setRutaProcesados( String rutaProcesados){
		this.rutaProcesados = rutaProcesados;
     }
     public Long getTiempoMonitoreo(){
		return this.tiempoMonitoreo;         
     }

     public void setTiempoMonitoreo( Long tiempoMonitoreo){
		this.tiempoMonitoreo = tiempoMonitoreo;
     }
     public String getLineaEncabezado(){
		return this.lineaEncabezado;         
     }

     public void setLineaEncabezado( String lineaEncabezado){
		this.lineaEncabezado = lineaEncabezado;
     }
     public String getProcesamientoSuperusuario(){
		return this.procesamientoSuperusuario;         
     }

     public void setProcesamientoSuperusuario( String procesamientoSuperusuario){
		this.procesamientoSuperusuario = procesamientoSuperusuario;
     }
     public java.math.BigDecimal getMontoMaximoProcesar(){
		return this.montoMaximoProcesar;         
     }

     public void setMontoMaximoProcesar( java.math.BigDecimal montoMaximoProcesar){
		this.montoMaximoProcesar = montoMaximoProcesar;
     }
     public String getEstado(){
		return this.estado;         
     }

     public void setEstado( String estado){
		this.estado = estado;
     }
     public String getUsuarioCreacion(){
		return this.usuarioCreacion;         
     }

     public void setUsuarioCreacion( String usuarioCreacion){
		this.usuarioCreacion = usuarioCreacion;
     }
     public java.util.Date getFechaCreacion(){
		return this.fechaCreacion;         
     }

     public void setFechaCreacion( java.util.Date fechaCreacion){
		this.fechaCreacion = fechaCreacion;
     }
     public String getUsuarioUltAct(){
		return this.usuarioUltAct;         
     }

     public void setUsuarioUltAct( String usuarioUltAct){
		this.usuarioUltAct = usuarioUltAct;
     }
     public java.util.Date getFechaUltAct(){
		return this.fechaUltAct;         
     }

     public void setFechaUltAct( java.util.Date fechaUltAct){
		this.fechaUltAct = fechaUltAct;
     }
     public String getEmailCliente(){
		return this.emailCliente;         
     }

     public void setEmailCliente( String emailCliente){
		this.emailCliente = emailCliente;
     }
     
     public String getPmHostSftp(){
		return this.pmHostSftp;         
     }

     public void setPmHostSftp( String pmHostSftp){
		this.pmHostSftp = pmHostSftp;
     }
     public String getPmPuertoSftp(){
		return this.pmPuertoSftp;         
     }

     public void setPmPuertoSftp( String pmPuertoSftp){
		this.pmPuertoSftp = pmPuertoSftp;
     }
     public String getPmUsuarioSftp(){
		return this.pmUsuarioSftp;         
     }

     public void setPmUsuarioSftp( String pmUsuarioSftp){
		this.pmUsuarioSftp = pmUsuarioSftp;
     }
     public String getPmPasswordSftp(){
		return this.pmPasswordSftp;         
     }

     public void setPmPasswordSftp( String pmPasswordSftp){
		this.pmPasswordSftp = pmPasswordSftp;
     }
     public String getPmLlaveSftp(){
		return this.pmLlaveSftp;         
     }

     public void setPmLlaveSftp( String pmLlaveSftp){
		this.pmLlaveSftp = pmLlaveSftp;
     }

	/**   Metodos que manejan los identificadores de los DTO foraneos */ 
    /**
     * Devuelve el atributo llave del DTO foraneo.
     * Verifica si es null antes de devolverlo.
     * @return llave del DTO del negocio maestro
     */
	public Long getCliente(){
		if(bsCliente!=null){
        	return bsCliente.getCliente();
		}
		return null;        	         
	}
    /**
     * Coloca el valor de la llave en el atributo espec&iacute;fico del DTO foraneo,
	 * crea una nueva instancia del objeto foraneo si este es nulo.
     * @param id Objeto que almacena la llave de un DTO que referencia a un negocio maestro.
     */
    public void setCliente( Long cliente){
		if(bsCliente != null && UtileriaDeTiposDeDatos.isEquals(cliente, bsCliente.getCliente()))
    		return;
			
		if(bsCliente==null || bsCliente.getCliente()!=null){
			bsCliente = new BsCliente();			
		}         
		bsCliente.setCliente(cliente);   
    }
    /**
     * Devuelve el atributo llave del DTO foraneo.
     * Verifica si es null antes de devolverlo.
     * @return llave del DTO del negocio maestro
     */
	public Long getIdVistaConvenio(){
		if(hthVistaConvenio!=null){
        	return hthVistaConvenio.getIdVistaConvenio();
		}
		return null;        	         
	}
    /**
     * Coloca el valor de la llave en el atributo espec&iacute;fico del DTO foraneo,

WebContent/WEB-INF/jsp/hthProcesoMonitoreo/jq/ver.jsp
<%@ taglib prefix="c"       uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt"     uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:if test="${ not empty locale}">
	<fmt:setLocale value="${ locale }" />
</c:if>
<fmt:bundle basename="com.ofbox.davivienda.h2h.resourceBundle.MessagesResources">
<c:if test="${ not empty hthProcesoMonitoreoEstado.enlaceDetalle}">
	<c:set var="detalle" value="${hthProcesoMonitoreoEstado.enlaceDetalle}"/>	
	<c:set var="detalleEnllavador" value="${detalle.enllavador}"/>
</c:if>		

<c:set var="nombre" value="hthProcesoMonitoreo"/>
<c:set var="ubicacion" value="ver"/>

<%@ include file="/WEB-INF/global/jsp/jq-header.jsp" %>

<form  name="mainForm" id="mainForm" action="${NewtPageRenderData.actionUrl}" method="post">
<c:if test="${ not empty detalle.cabecera}">
    <jsp:include page="/WEB-INF/jsp/${detalle.cabecera.locacion}/jq/cabecera.jsp" />
</c:if>
<div id="mainContent">
	<div class="breadCrumbHolder module" style="margin-bottom: 3px;">
<div id="breadcrumb" class="breadCrumb module ui-widget ui-widget-content" style="width: 99%;">
<ul>
	<li><a href="${ctx}/inicio/blank/ria"> HOME </a> </li>
<c:if test="${ not empty ubicacionAplicacion.ruta }">
	<input type="hidden" name="idUbicacionAplicacionActual" id="idUbicacionAplicacionActual" value="${ ubicacionAplicacion.idUbicacionAplicacionActual }"/>
	<c:forEach items="${ ubicacionAplicacion.ruta }" var="ub">
		<li><a href="javascript: doSubmitBreadcrumb('<c:out value="${ ub.submit }"/>', '<c:out value="${ ub.id }"/>')"><c:out value="${ ub.label }" escapeXml="false" /></a>  </li> 
	</c:forEach>			
</c:if>
	<li><fmt:message key="hthProcesoMonitoreo.bc.etiqueta.ver" /></li>
</ul>
</div>
	<input type="hidden" name="id_ubicacion_retorno" id="id_ubicacion_retorno" value=""/>
</div>
	
<%--<div id="iTitle" class="ui-state-default ui-widget-content ui-corner-all">
	<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.ver.titulo"/>
</div>--%>

    <div id="iProcessing" style="visibility: hidden" align="center">
    	<img src="${ctx}/include/images/design/processing_request.gif"></img>
    </div>
	<input type="hidden" id="pageLoc" name="pageLoc" value="ver"/>
    <input type="hidden" id="eag" name="eag" value="${eag}"/>
    <input type="hidden" id="movimientoPagina" name="movimientoPagina"/>
    <input type="hidden" id="columna" name="columna"/>
    <input type="hidden" id="fenixf31seguridad" name="fenixf31seguridad" value="<c:out value='${fenixf31seguridad}' />" />
	<!-- valores de llaves -->
	
	
	<input type="hidden" id="nombreBusqueda" name="nombreBusqueda"/>

<div id="action-buttons">
<div id="action-bar">
	<button id="btnCancelar" type="button" name="regresar" onClick="doSubmit<c:if test="${ not empty detalle.cabecera}">Async</c:if>('hthProcesoMonitoreo/cancelarVer');"><fmt:message key="globales.formulario.boton.regresar"/></button>
</div>
</div>
<br />

<!-- datos de formulario -->
<div class="ui-widget ui-widget-content ui-corner-all" style="width: 99%">
		<div id="formInputHeader" class="ui-widget ui-widget-header ui-corner-top" style="padding-left: 5px;"> 
			<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.ver.titulo"/> 
		</div>
		
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.Cliente"/>
			</span>	 
			
			<span class="formvalue">
	            [${hthProcesoMonitoreo.cliente}] - ${hthProcesoMonitoreo.bsCliente.nombre}
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.IdVistaConvenio"/>
			</span>	 
			
			<span class="formvalue">
	            [${hthProcesoMonitoreo.idVistaConvenio}] - ${hthProcesoMonitoreo.hthVistaConvenio.nombre}
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.Empresaodepto"/>
			</span>	 
			
			<span class="formvalue">
	            [${hthProcesoMonitoreo.empresaodepto}] - ${hthProcesoMonitoreo.bsEmpresaodepto.nombre}
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.ConvenioPEACH"/>
			</span>	 
			
			<span class="formvalue">
			<c:if test="${hthProcesoMonitoreo.convenioPEACH == 'PE'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.PE"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.convenioPEACH == 'ACH'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.ACH"/></c:if>
			<c:if test="${hthProcesoMonitoreo.convenioPEACH == 'PS'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.PS"/></c:if>
			<c:if test="${hthProcesoMonitoreo.convenioPEACH == 'TEXT'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.TEXT"/></c:if>	
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.ConvenioNombre"/>
			</span>	 
			
			<span class="formvalue">
			<c:if test="${hthProcesoMonitoreo.convenioNombre == 'PLANILLA'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.PLANILLA"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.convenioNombre == 'PROVEEDORES'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.PROVEEDORES"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.convenioNombre == 'COBROS'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.COBROS"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.convenioNombre == 'CHEQUES'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.CHEQUES"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.convenioNombre == 'ACH_PLANILLA'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.PAGOPLANILLASACH"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.convenioNombre == 'ACH_PROVEEDORES'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.PAGOPROVEEDORESACH"/></c:if>	
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.NombreArchivo"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.nombreArchivo}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.RutaSftp"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.rutaSftp}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.RutaArchivosIn"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.rutaArchivosIn}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.RutaArchivosOut"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.rutaArchivosOut}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.RutaProcesados"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.rutaProcesados}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.TiempoMonitoreo"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.tiempoMonitoreo}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.LineaEncabezado"/>
			</span>	 
			
			<span class="formvalue">
			<c:if test="${hthProcesoMonitoreo.lineaEncabezado == 'S'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.Si"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.lineaEncabezado == 'N'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.No"/></c:if>	
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.IdFormatoEncabezado"/>
			</span>	 
			
			<span class="formvalue">
	            [${hthProcesoMonitoreo.idFormatoEncabezado}] - ${hthProcesoMonitoreo.hthFormatoEncabezado.nombreFormato}
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.ProcesamientoSuperusuario"/>
			</span>	 
			
			<span class="formvalue">
			<c:if test="${hthProcesoMonitoreo.procesamientoSuperusuario == 'S'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.Si"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.procesamientoSuperusuario == 'N'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.No"/></c:if>	
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.IdFormatoDetalle"/>
			</span>	 
			
			<span class="formvalue">
	            [${hthProcesoMonitoreo.idFormatoDetalle}] - ${hthProcesoMonitoreo.hthFormato.nombreFormato}
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.MontoMaximoProcesar"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.montoMaximoProcesar}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.Estado"/>
			</span>	 
			
			<span class="formvalue">
			<c:if test="${hthProcesoMonitoreo.estado == 'A'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.Activado"/></c:if>	
			<c:if test="${hthProcesoMonitoreo.estado == 'D'}"><fmt:message key="hthProcesoMonitoreo.formulario.comboLabel.Desactivado"/></c:if>	
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.UsuarioCreacion"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.usuarioCreacion}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.FechaCreacion"/>
			</span>	 
			
			<span class="formvalue">
                <fmt:formatDate pattern="dd-MM-yyyy" value="${hthProcesoMonitoreo.fechaCreacion}" />
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.UsuarioUltAct"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.usuarioUltAct}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.FechaUltAct"/>
			</span>	 
			
			<span class="formvalue">
                <fmt:formatDate pattern="dd-MM-yyyy" value="${hthProcesoMonitoreo.fechaUltAct}" />
			</span>
			
			<span class="clearer"></span>
		</div>
	
	
		<div class="row">
			<span class="label ui-state-default"> 
				<fmt:message key="hthProcesoMonitoreo.formulario.etiqueta.EmailCliente"/>
			</span>	 
			
			<span class="formvalue">
                ${hthProcesoMonitoreo.emailCliente}		    
			</span>
			
			<span class="clearer"></span>
		</div>
	
		
</div>		
</div>
</form>

<%@ include file="/WEB-INF/global/jsp/jq-footer.jsp" %>
</fmt:bundle>